services:
  producer:
    build: producer
    depends_on:
      - rmq
  consumer:
    build: consumer
    depends_on:
      - rmq
  rmq:
    build: rmq
    hostname: rabbitmq
    environment:
      LOG: debug
    ports:
      # HOST:CONTAINER
      - 15672:15672
